### ISSUE TITLE
No such file or directory...

### ISSUE THREAD

**Issue by bisonbleu** [endel/php-code-downgrade#1]
Hi, can you provide a more detailed guide on how to use your utility? I'm getting the following errors:

ren$ ./php-code-downgrade commerce_rules_extra

> Warning:
> require(/Users/ren/Desktop/php-code-downgrade-master/vendor/autoload.php):
> failed to open stream: No such file or directory in
> /Users/ren/Desktop/php-code-downgrade-master/php-code-downgrade on
> line 4
> 
> Fatal error: require(): Failed opening required
> '/Users/ren/Desktop/php-code-downgrade-master/vendor/autoload.php'
> (include_path='.:') in
> /Users/ren/Desktop/php-code-downgrade-master/php-code-downgrade on
> line 4

There is no 'vendor' directory in the zip file?

Thanks

**Comment by endel** [comment]
Hi @bisonbleu, thanks for checking out this project.

This error means that there's no such file `vendor/autoload.php`, which are the dependencies of this project that you need to install through `composer install`.

Just run `composer install` in the root of the project then you'll be able to run the utility.

Please let me know if you need help with something.

Cheers

**Comment by bisonbleu** [comment]
Hi @endel, thanks for the quick Sunday reply :+1:

OK, Composer, I'll find the time and give it a try this week. Cheers!
p.s. An online service where one could just upload PHP files and have them downgraded would be awesome don't you think? ;-)
